# Install K8s binaries
# Documentation at
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md
# https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md

- name: Copy k8s binaries to /usr/local/bin
  become: true
  copy:
    src: "packages/k8s-{{ k8s_version }}-server/kubernetes/server/bin/{{ item }}"
    dest: /usr/local/bin
    mode: '0755'
  with_items:
    - kubelet
    - kube-proxy

- name: Create k8s directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/kubelet
    - /var/lib/kubelet/pods
    - /var/lib/kube-proxy

- name: Copy worker key to kubelet configuration
  become: true
  copy:
    src: "certificates/{{ cluster_name }}-worker-{{ inventory_hostname }}.key"
    dest: "/var/lib/kubelet/{{ cluster_name }}-worker-{{ inventory_hostname }}.key"
    mode: '0600'

- name: Copy certificates to kubelet configuration
  become: true
  copy:
    src: "certificates/{{ item }}"
    dest: "/var/lib/kubelet/{{ item }}"
    mode: '0644'
  with_items:
    - "{{ cluster_name }}-worker-{{ inventory_hostname }}.crt"
    - "{{ cluster_name }}-ca.crt"

- name: Copy sytemctl service configurations to the node
  become: true
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - kubelet.service
    - kube-proxy.service

- name: Copy kubelet kubeconfig to the node
  become: true
  copy:
    src: "configuration/{{ inventory_hostname }}.kubeconfig"
    dest: /var/lib/kubelet/kubeconfig
    mode: '0600'

- name: Copy kubelet-config.yaml configuration to the node
  become: true
  template:
    src: templates/kubelet_config_yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml

- name: Copy kube-proxy kubeconfig to the node
  become: true
  copy:
    src: configuration/kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/kubeconfig
    mode: '0600'

- name: Copy kube-proxy-config.yaml configuration to the node
  become: true
  template:
    src: templates/kube_proxy_config_yaml.j2
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable systemctl services
  become: true
  systemd:
    enabled: yes
    masked: no
    name: "{{ item }}"
  with_items:
    - kubelet
    - kube-proxy

- name: start systemctl services
  become: true
  systemd:
    state: restarted
    name: "{{ item }}"
  with_items:
    - kubelet
    - kube-proxy
