# include other YAML files with tasks here
- include: generate_ssl_ca.yml
- include: generate_admin_certificate.yml
- include: generate_kube-controller-manager_certificate.yml
- include: generate_kube-proxy_certificate.yml
- include: generate_kube-scheduler_certificate.yml
- include: generate_kube-apiserver_certificate.yml
- include: generate_etcd-cluster__certificate.yml
