repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.14.3
    hooks:
    -   id: detect-secrets
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: fix-byte-order-marker
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-toml
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: check-ast
    -   id: check-executables-have-shebangs
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    -   id: shell-lint
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.3.6
    hooks:
    -   id: nbqa
    -   id: nbqa-black
