- hosts: all
  gather_facts: no
  tasks:
  - name: Ping all nodes
    ping:
    ignore_errors: yes

  - name: Wait for system to become reachable
    wait_for_connection:
    register: task_register_var
    until: task_register_var is not failed
    retries: 5
    ignore_errors: yes

  - name: Gather facts for first time
    setup:

# High level instructions for which tasks apply to which hosts
- name: apply local configuration to servers listed in hosts
  hosts: all
  user: "{{ deploy_user }}"
  roles:
    - common
