# High level instructions for which tasks apply to which hosts
- name: apply local configuration to servers listed in hosts
  hosts: localhost
  user: "{{ deploy_user }}"
  roles:
    - generate-configuration

- name: Generate etcd configuration
  hosts: etcd_hosts
  user: "{{ deploy_user }}"
  roles:
    - generate-etcd-configuration

