# High level instructions for which tasks apply to which hosts
- name: Setup etcd hosts
  hosts: etcd_hosts
  user: "{{ deploy_user }}"
  roles:
    - etcd-host

- name: etcdctl endpoint health
  hosts: etcd_hosts
  user: "{{ deploy_user }}"
  serial: 1
  tasks:
    - name: etcd smoke test
      become: yes
      shell: 'etcdctl --endpoints=https://{{ ansible_host }}:2379 --cacert=/etc/etcd/"{{ cluster_name }}"-ca.crt --cert=/etc/etcd/"{{ cluster_name }}"-etcd.crt --key=/etc/etcd/"{{ cluster_name }}"-etcd.key endpoint health'
