- name: Network setup
  hosts: workers
  user: "{{ deploy_user }}"
  tasks:
  # - name: Copy CNI
  #   become: true
  #   copy:
  #     src: "/etc/cni/net.d/{{ item }}"
  #     dest: /etc/cni/net.d/
  #   with_items:
  #     - 100-crio-bridge.conf
  #     - 200-loopback.conf
  #     - 87-podman-bridge.conflist

  #  - name: Deploy Flannel Container Networking
  #    shell: 'kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml'

  #  - name: Deploy Weave Container Networking
  #    shell: 'kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"''

  #  - name: Deploy CoreDNS
  #    shell: 'kubectl apply -f templates/coredns.yml --kubeconfig configuration/admin.kubeconfig'


   - name: test
     debug:
       msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"

   - name: test
     debug:
       msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"

   - name: test
     debug:
       msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
