- name: Network setup
  hosts: localhost
  user: "{{ deploy_user }}"
  tasks:
  # - name: Deploy CoreDNS
  #   shell: 'kubectl apply -f templates/coredns.yml --kubeconfig configuration/admin.kubeconfig'
  #   groups['workers'].index(item)
    - name: Creating routing tables for cni
      debug:
        msg: "{{ service_cidr | next_nth_usable(10) }}"
