- name: Run on all hosts
  hosts: all
  user: "{{ deploy_user }}"
  tasks:
    - name: Disable Services
      become: true
      systemd:
      enabled: no
      masked: no
      name:
        - kube-apiserver
        - kube-scheduler
        - kube-controller-manager

    - name: Stop Services
      become: true
      systemd:
      state: stopped
      name:
        - kube-apiserver
        - kube-scheduler
        - kube-controller-manager

    - name: systemd reload
      become: true
      systemd:
      daemon_reload: yes

#   - name: Reboot system
#      become: true
#      shell: /sbin/shutdown -r now
#      async: 300
#      poll: 0
#      ignore_errors: true
