- name: Run on all hosts
  hosts: all
  user: "{{ deploy_user }}"
  tasks:
   - name: Reboot system
     become: true
     shell: /sbin/shutdown -r now
     async: 300
     poll: 0
     ignore_errors: true
