- name: Run on all hosts
  hosts: all
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - crio
   - name: Disable services
     become: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - crio
   - name: Remove crio files
     become: true
     file:
       path: /var/lib/crio
       state: absent

- name: Run on etcd hosts
  hosts: etcd_hosts
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - etcd
   - name: Disable services
     become: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - etcd
   - name: Remove etcd database
     become: true
     file:
       path: /var/lib/etcd
       state: absent

- name: Run on masters
  hosts: masters
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - kube-apiserver
       - kube-scheduler
       - kube-controller-manager
   - name: Disable services
     become: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - kube-apiserver
       - kube-scheduler
       - kube-controller-manager
   - name: Remove K8s files
     become: true
     file:
       path: /var/lib/kubernetes
       state: absent

- name: Run on workers
  hosts: workers
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - kubelet
       - kube-proxy
   - name: Disable services
     become: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - kubelet
       - kube-proxy
   - name: Terminate conmon processes
     become: true
     shell: 'killall conmon; echo OK'
   - name: Unmount all tmpfs pod direrctories
     become: true
     shell: 'mount | grep "/var/lib/kubelet/" && umount `mount | grep "/var/lib/kubelet/" | sed s/"tmpfs on "// | sed s/" type.*"//`; echo OK'
   - name: Remove kubelet files
     become: true
     file:
       path: /var/lib/kubelet
       state: absent
   - name: Remove kube-proxy files
     become: true
     file:
       path: /var/lib/kube-proxy
       state: absent
   - name: Remove cni files
     become: true
     file:
       path: /var/lib/cni
       state: absent
# Look if the bridge is still there: brctl show
# Look if the link is still there: ip link
# and: ip link delete cni0; ip link delete flannel.1
   - name: Remove flannel files cni configuration
     become: true
     file:
       path: /etc/cni/net.d/10-flannel.conflist
       state: absent

- name: Reboot all hosts
  hosts: all
  user: "{{ deploy_user }}"
  tasks:
   - name: Reboot system
     become: true
     shell: /sbin/shutdown -r +1
     async: 300
     poll: 0
     ignore_errors: true
