- name: Run on all hosts
  hosts: all
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     ignore_errors: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - crio
       - docker
   - name: Disable services
     become: true
     ignore_errors: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - crio
       - docker
   - name: Remove container runtime
     become: true
     apt:
       name:
         - docker.io
         - cri-o-{{ crio_version }}
         - cri-o-runc
         - cri-tools
         - podman
         - podman-plugins
         - skopeo
         - catatonit
         - fuse-overlayfs
         - conmon
         - containers-common
         - containers-golang
         - containers-image
         - containernetworking-plugins
         - libslirp0
         - slirp4netns
         - uidmap
         - varlink
       state: absent
   - name: Remove all Kubernetes binaries
     become: true
     file:
       path: "{{ item }}"
       state: absent
     with_fileglob: "/usr/local/bin/kube*"
   - name: Remove all etcd binaries
     become: true
     file:
       path: "{{ item }}"
       state: absent
     with_fileglob: "/usr/local/bin/etcd*"

- name: Run on etcd hosts
  hosts: etcd_hosts
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - etcd
   - name: Disable services
     become: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - etcd
   - name: Remove etcd database
     become: true
     file:
       path: /var/lib/etcd
       state: absent

- name: Run on masters
  hosts: masters
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - kube-apiserver
       - kube-scheduler
       - kube-controller-manager
   - name: Disable services
     become: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - kube-apiserver
       - kube-scheduler
       - kube-controller-manager
   - name: Remove K8s files
     become: true
     file:
       path: /var/lib/kubernetes
       state: absent

- name: Run on workers
  hosts: workers
  user: "{{ deploy_user }}"
  tasks:
   - name: Stop services
     become: true
     systemd:
       state: stopped
       name: "{{ item }}"
     with_items:
       - kubelet
       - kube-proxy
   - name: Disable services
     become: true
     systemd:
       enabled: no
       name: "{{ item }}"
       masked: no
     with_items:
       - kubelet
       - kube-proxy
   - name: Remove kubelet files
     become: true
     file:
       path: /var/lib/kubelet
       state: absent
   - name: Remove kube-proxy files
     become: true
     file:
       path: /var/lib/kube-proxy
       state: absent

- name: Reboot all hosts
  hosts: all
  user: "{{ deploy_user }}"
  tasks:
   - name: Reboot system
     become: true
     shell: /sbin/shutdown -r +1
     async: 300
     poll: 0
     ignore_errors: true
