- hosts: all
  gather_facts: no
  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
    register: task_register_var
    until: task_register_var is not failed
    retries: 5
    ignore_errors: yes

- name: Reboot all hosts
  hosts: all
  user: "{{ deploy_user }}"
  tasks:
   - name: Reboot system
     become: true
     shell: /sbin/shutdown -r +1
     async: 300
     poll: 0
     ignore_errors: true
