- name: Copy k3s binary to /usr/local/bin
  become: true
  copy:
    src: "packages/k3s-arm64"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: '0755'

- name: Copy K3s service file
  become: true
  template:
    src: "templates/k3s-worker.service.j2"
    dest: "/etc/systemd/system/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  become: true
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
