# entry point for creating K8s configuration files
- name: Create directory for configuration files
  delegate_to: localhost
  file:
    path: configuration
    state: directory

- name: Create kube-controller-manager.service configuration files
  delegate_to: localhost
  template:
    src: templates/kube-controller-manager_service.j2
    dest: configuration/kube-controller-manager_service

- name: Create kube-scheduler.service configuration files
  delegate_to: localhost
  template:
    src: templates/kube-scheduler_service.j2
    dest: configuration/kube-scheduler_service
