# entry point for creating K8s configuration files
- name: Create directory for configuration files
  delegate_to: localhost
  file:
    path: configuration
    state: directory

- name: Create etcd cluster string
  set_fact:
    etcd_cluster_member: "https://{{ ansible_host }}:2380"

- name: Assemble etcd cluster string
  set_fact:
    etcd_cluster: "{{ groups['etcd_hosts'] | map('extract', hostvars, ['etcd_cluster_member']) | join(',') }}"

- name: Create kube-apiserver.service configuration files
  delegate_to: localhost
  template:
    src: templates/kube-apiserver_service.j2
    dest: configuration/kube-apiserver-{{ inventory_hostname }}_service

- name: Create kube-controller-manager.service configuration files
  delegate_to: localhost
  template:
    src: templates/kube-controller-manager_service.j2
    dest: configuration/kube-controller-manager_service

- name: Create kube-scheduler.service configuration files
  delegate_to: localhost
  template:
    src: templates/kube-scheduler_service.j2
    dest: configuration/kube-scheduler_service
