- name: Add rook-ceph operator helm repo
  community.kubernetes.helm_repository:
    name: rook-release
    repo_url: "https://charts.rook.io/release"

- name: Deploy latest version of the rook-ceph chart
  community.kubernetes.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    release_namespace: rook-ceph
    create_namespace: true

- name: Create rook-ceph cluster
  community.kubernetes.k8s:
    apply: yes
    state: present
    src: templates/rook-ceph-cluster.yml
    validate:
      fail_on_error: yes

- name: Deploy rook-ceph toolbox
  community.kubernetes.k8s:
    state: present
    src: templates/rook-ceph-toolbox.yml
    validate:
      fail_on_error: yes
