# Create encryption key and config

- name: Check if new encryption config is required
  stat:
    path: certificates/encryption-config.yaml
  register: need_config

- name: Create secret for encryption
  set_fact:
          encryption_key: "{{ lookup('password', '/dev/null length=32') | b64encode }}"
  when: need_config.stat.exists == False

- name: Create configuration file for enryption
  template:
    src: templates/encryption_config.j2
    dest: certificates/encryption-config.yaml
  when: need_config.stat.exists == False
