# Create the certificate for the kube-proxy

- name: Generate an OpenSSL 2048 bit private RSA key for kube-proxy
  openssl_privatekey:
    path: "certificates/{{ cluster_name }}-kube-proxy.key"
    size: 2048
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request for kube-proxy
  openssl_csr:
    path: "certificates/{{ cluster_name }}-kube-proxy.csr"
    privatekey_path: "certificates/{{ cluster_name }}-kube-proxy.key"
    subject: "CN=system:kube-proxy"

- name: Sign the kube-proxy key with CA to obtain kube-proxy certificate
  openssl_certificate:
    path: "certificates/{{ cluster_name }}-kube-proxy.crt"
    csr_path: "certificates/{{ cluster_name }}-kube-proxy.csr"
    ownca_path: "certificates/{{ cluster_name }}-ca.crt"
    ownca_privatekey_path: "certificates/{{ cluster_name }}-ca.key"
    provider: ownca
