# Creating the ertificate that will be used in the kubeconfig for admin access

- name: Generate an OpenSSL 2048 bit private RSA key for admin access
  openssl_privatekey:
    path: "certificates/{{ cluster_name }}-admin.key"
    size: 2048
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request for admin access
  openssl_csr:
    path: "certificates/{{ cluster_name }}-admin.csr"
    privatekey_path: "certificates/{{ cluster_name }}-admin.key"
    subject: "CN=admin,O=system:masters"

- name: Sign the admin key with CA to obtain admin certificate
  openssl_certificate:
    path: "certificates/{{ cluster_name }}-admin.crt"
    csr_path: "certificates/{{ cluster_name }}-admin.csr"
    ownca_path: "certificates/{{ cluster_name }}-ca.crt"
    ownca_privatekey_path: "certificates/{{ cluster_name }}-ca.key"
    provider: ownca
