# entry point for creating new SSL Cartificate Authority
# https://github.com/githubixx/ansible-role-kubernetes-ca
# https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md
- name: Create directory for certificates
  file:
    path: certificates
    state: directory

- name: Generate an OpenSSL 2048 bit private RSA key
  openssl_privatekey:
    path: "certificates/{{ cluster_name }}-service-account.key"
    size: 2048
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "certificates/{{ cluster_name }}-service-account.csr"
    privatekey_path: "certificates/{{ cluster_name }}-service-account.key"
    subject: "CN=system:service-accounts"

- name: Sign the service-account key with CA to obtain service-account certificate
  openssl_certificate:
    path: "certificates/{{ cluster_name }}-service-account.crt"
    csr_path: "certificates/{{ cluster_name }}-service-account.csr"
    ownca_path: "certificates/{{ cluster_name }}-ca.crt"
    ownca_privatekey_path: "certificates/{{ cluster_name }}-ca.key"
    provider: ownca
