# entry point for common playbook
- name: apt-get update and apt-get upgrade
  become: true
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400 #Only update if cache is older than one day
  register: apt_update_upgrade

- name: apt-get autoclean
  become: true
  apt:
    autoclean: yes
  when: apt_update_upgrade.changed == True

- name: apt-get autoremove --purge
  become: true
  apt:
    autoremove: yes
    purge: yes
  when: apt_update_upgrade.changed == True

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: need_reboot

- name: Reboot systems that need it
  become: true
  shell: /sbin/shutdown -r now
  async: 300
  poll: 0
  ignore_errors: true
  when: need_reboot.stat.exists == True

- name: Wait for rebooted systems to reconnect
  wait_for_connection:
    delay: 60
    timeout: 300
  when: need_reboot.stat.exists == True

- name: apt-get autoremove --purge after reboot
  become: true
  apt:
    autoremove: yes
    purge: yes
  when: need_reboot.stat.exists == True
