# Install etcd
# Documentation at
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md
# https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md
# https://github.com/etcd-io/etcd/releases

- name: Copy etcd binary to /usr/local/bin
  become: true
  copy:
    src: packages/etcd-{{ etcd_version }}-linux-arm64/etcd
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Copy etcdctl binary to /usr/local/bin
  become: true
  copy:
    src: packages/etcd-{{ etcd_version }}-linux-arm64/etcdctl
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Create /etc/etcd/ directory
  become: true
  file:
    path: /etc/etcd/
    state: directory

- name: Create /var/lib/etcd directory
  become: true
  file:
    path: /var/lib/etcd
    state: directory

- name: Copy CA certificate to etcd configuration
  become: true
  copy:
    src: certificates/{{ cluster_name }}-ca.crt
    dest: /etc/etcd/{{ cluster_name }}-ca.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy etcd certificate to etcd configuration
  become: true
  copy:
    src: certificates/{{ cluster_name }}-etcd.crt
    dest: /etc/etcd/{{ cluster_name }}-etcd.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy etcd key to etcd configuration
  become: true
  copy:
    src: certificates/{{ cluster_name }}-etcd.key
    dest: /etc/etcd/{{ cluster_name }}-etcd.key
    owner: root
    group: root
    mode: '0600'

- name: Copy etcd configuration to the node
  become: true
  copy:
    src: configuration/etcd-{{ inventory_hostname }}_service
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable etcd
  become: true
  systemd:
    enabled: yes
    masked: no
    name: etcd

- name: start etcd
  become: true
  systemd:
    state: restarted
    name: etcd

# After etcd has restarted, the following command can be used to check:
# sudo ETCDCTL_API=3 etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/etcd/{{ cluster_name }}-ca.crt --cert=/etc/etcd/{{ cluster_name }}-etcd.crt --key=/etc/etcd/{{ cluster_name }}-etcd.key member list
