# entry point for creating K8s configuration files
- name: Create directory for configuration files
  file:
    path: configuration
    state: directory

- name: Create kube-controller-manager configuration file, step 1
  shell: 'kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority=certificates/{{ cluster_name }}-ca.crt \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig=configuration/kube-controller-manager.kubeconfig'

- name: Create kube-controller-manager configuration file, step 2
  shell: 'kubectl config set-credentials system:kube-controller-manager \
    --client-certificate=certificates/{{ cluster_name }}-kube-controller-manager.crt \
    --client-key=certificates/{{ cluster_name }}-kube-controller-manager.key \
    --embed-certs=true \
    --kubeconfig=configuration/kube-controller-manager.kubeconfig'

- name: Create kube-controller-manager configuration file, step 3
  shell: 'kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user=system:kube-controller-manager \
    --kubeconfig=configuration/kube-controller-manager.kubeconfig'

- name: Create kube-controller-manager configuration file, step 4
  shell: 'kubectl config use-context default --kubeconfig=configuration/kube-controller-manager.kubeconfig'

- name: Create kube-controller-manager.service configuration files
  template:
    src: templates/kube-controller-manager_service.j2
    dest: configuration/kube-controller-manager_service
