# entry point for creating K8s configuration files
- name: Create directory for configuration files
  file:
    path: configuration
    state: directory

- name: Check if new config is required
  stat:
    path: configuration/kubelet_service
  register: need_config

- name: Create admin configuration file
  template:
    src: templates/kubelet_service.j2
    dest: configuration/kubelet_service
  when: need_config.stat.exists == False
