# entry point for creating K8s configuration files
- name: Create directory for configuration files
  file:
    path: configuration
    state: directory

- name: Create kube-scheduler configuration file
  template:
    src: templates/kube-scheduler_kubeconfig.j2
    dest: configuration/kube-scheduler.kubeconfig
