# entry point for creating K8s configuration files
- name: Create directory for configuration files
  file:
    path: configuration
    state: directory

- name: Create kube-controller-manager configuration file
  template:
    src: templates/kube-controller-manager_kubeconfig.j2
    dest: configuration/kube-controller-manager.kubeconfig
