# entry point for creating K8s configuration files
- name: Create directory for configuration files
  file:
    path: configuration
    state: directory

- name: Check if new config is required
  stat:
    path: configuration/kube-scheduler.kubeconfig
  register: need_config

- name: Create kube-scheduler configuration file
  template:
    src: templates/kube-scheduler_kubeconfig.j2
    dest: configuration/kube-scheduler.kubeconfig
  when: need_config.stat.exists == False
