# Downloading k8s server binaries

- name: Check if k8s {{ k8s_version }} server binary download is required
  stat:
    path: packages/kubernetes-server-v{{ k8s_version }}-linux-arm64.tar.gz
  register: k8s_server_downloaded

- name: Download k8s {{ k8s_version }} server package
  get_url:
    url: https://dl.k8s.io/v{{ k8s_version }}/kubernetes-server-linux-arm64.tar.gz
    dest: packages/kubernetes-server-v{{ k8s_version }}-linux-arm64.tar.gz
  when: k8s_server_downloaded.stat.exists == False

- name: Check if k8s {{ k8s_version }} server archive unpack is required
  stat:
    path: packages/packages/k8s-{{ k8s_version }}-server
  register: k8s_server_unpacked

- name: Create directory for k8s server {{ k8s_version }} package unpack
  file:
    path: packages/k8s-{{ k8s_version }}-server
    state: directory
  when: k8s_server_downloaded.stat.exists == False

# unarchive module would be better, it's' currently buggy and can't handle tgz'
- name: Extract k8s server {{ k8s_version }} package
  shell: "cd packages ; tar xzf kubernetes-server-v{{ k8s_version }}-linux-arm64.tar.gz -C k8s-{{ k8s_version }}-server"
  when: k8s_server_unpacked.stat.exists == False
