# include other YAML files with tasks here
- include: generate_kube-proxy_kubeconfig.yml
- include: generate_kube-controller-manager_kubeconfig.yml
- include: generate_kube-scheduler_kubeconfig.yml
- include: generate_admin_kubeconfig.yml
