# include other YAML files with tasks here
- include: generate_kubelet_config.yml
- include: generate_kube-proxy_kubeconfig.yml
- include: generate_kube-controller-manager_kubeconfig.yml
- include: generate_kube-scheduler_kubeconfig.yml
- include: generate_admin_kubeconfig.yml
- include: generate_encryption_config.yml
- include: etcd_download.yml
- include: crictl_download.yml
- include: k8s_download.yml
