# Operating system things: cgroups, package installations etc.

# This is the right place for Ubuntu 20.04. In earlier versions, the correct
# file used to be /boot/firmware/btcmd.txt or /boot/firmware/nobtcmd.txt
- name: make sure cgroups are enabled (Ubuntu 18.04)
  become: true
  template:
    src: templates/{{ item }}-Ubuntu-18.04.j2
    dest: /boot/firmware/{{ item }}.txt
  register: cgroups_enabled
  with_items:
    - nobtcmd
    - btcmd
  when: hostvars[inventory_hostname].ansible_distribution == "Ubuntu" and hostvars[inventory_hostname].ansible_distribution_major_version == "18"

- name: make sure cgroups are enabled (Ubuntu 20.04)
  become: true
  template:
    src: templates/cmdline-Ubuntu-20.04.j2
    dest: /boot/firmware/cmdline.txt
  register: cgroups_enabled
  when: hostvars[inventory_hostname].ansible_distribution == "Ubuntu" and hostvars[inventory_hostname].ansible_distribution_major_version == "20"

- name: make sure necessary packages are installed
  become: true
  apt:
    pkg:
    - python3-apt
    - runc
    - socat
    - conntrack
    - ipset
    - dnsmasq
    - resolvconf
    - net-tools

- name: apt-get update and apt-get upgrade
  become: true
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400 #Only update if cache is older than one day
  register: apt_update_upgrade

- name: apt-get autoclean
  become: true
  apt:
    autoclean: yes
  when: apt_update_upgrade.changed == True

- name: apt-get autoremove --purge
  become: true
  apt:
    autoremove: yes
    purge: yes
  when: apt_update_upgrade.changed == True

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: need_reboot

- name: Reboot systems that need it
  become: true
  shell: /sbin/shutdown -r +1
  async: 300
  poll: 0
  ignore_errors: true
  when: cgroups_enabled.changed or need_reboot.stat.exists == True

- name: Wait for rebooted systems to reconnect
  wait_for_connection:
    delay: 60
    timeout: 300
  when: cgroups_enabled.changed or need_reboot.stat.exists == True

- name: apt-get autoremove --purge after reboot
  become: true
  apt:
    autoremove: yes
    purge: yes
  when: need_reboot.stat.exists == True

- name: Remove annoying motd messages
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/50-motd-news

- name: make sure all nodes are available in /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: '{{ hostvars[item].ansible_host }} {{ item }}'
  with_items: "{{ groups['all'] }}"
