# entry point for common playbook
- name: make sure necessary packages are installed
  become: true
  apt:
    pkg:
    - python3-apt
    - runc
    - socat
    - conntrack
    - ipset
    - dnsmasq
    - resolvconf
    - net-tools

# This is the right place for Ubuntu 20.04. In earlier versions, the correct
# file used to be /boot/firmware/btcmd.txt or /boot/firmware/nobtcmd.txt
- name: make sure cgroups are enabled
  become: true
  template:
    src: templates/cmdline.j2
    dest: /boot/firmware/cmdline.txt
  register: cgroups_enabled

- name: Reboot systems that need it
  become: true
  shell: /sbin/shutdown -r +1
  async: 300
  poll: 0
  ignore_errors: true
  when: cgroups_enabled.changed

- name: Wait for rebooted systems to reconnect
  wait_for_connection:
    delay: 60
    timeout: 300
  when: cgroups_enabled.changed

- name: Remove annoying motd messages
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/50-motd-news

- name: make sure all nodes are available in /etc/hosts
  become: true
  lineinfile: 
    path: /etc/hosts
    line: '{{ hostvars[item].ansible_host }} {{ item }}'
  with_items: "{{ groups['all'] }}"

