# entry point for common playbook
- name: make sure necessary packages are installed
  become: true
  apt:
    pkg:
    - python3-apt
    - unzip
    - socat

- name: make sure cgroups are enabled
  become: true
  template:
    src: templates/cmdline.j2
    dest: /boot/firmware/nobtcmd.txt

- name: make sure cgroups are enabled
  become: true
  template:
    src: templates/cmdline.j2
    dest: /boot/firmware/btcmd.txt

