# Cleanup after upgrade/update/install

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: need_reboot

- name: Reboot systems that need it
  become: true
  shell: /sbin/shutdown -r +1
  async: 300
  poll: 0
  ignore_errors: true
  when: cgroups_enabled.changed or need_reboot.stat.exists == True

- name: Wait for rebooted systems to reconnect
  wait_for_connection:
    delay: 60
    timeout: 300
  when: cgroups_enabled.changed or need_reboot.stat.exists == True

- name: apt-get autoremove --purge after reboot
  become: true
  apt:
    autoremove: yes
    purge: yes
  when: need_reboot.stat.exists == True
