# Adding the crio repository and install
# Documentation at
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
# https://github.com/cri-o/cri-o
# https://medium.com/@raghwendrasingh1819/diy-kubernetes-cluster-with-cri-o-container-runtime-ubuntu-xenial-53e967c33dd9

- name: add crio apt-key for {{ os_used }} {{ os_version }}
  become: true
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x{{ os_used }}_{{ os_version }}/Release.key"
    state: present

- name: add crio apt repository {{ os_used }} {{ os_version }}
  become: true
  apt_repository:
    repo: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ os_used }}_{{ os_version }}/ /'
    state: present
    filename: devel:kubic:libcontainers:stable.list
    update_cache: yes

- name: install crio {{ crio_version }}
  become: true
  apt:
    name: cri-o-{{ crio_version }}
    state: present
    update_cache: yes

# sudo make install-cni install-conmon install-crio install-pinns install-runc
# curl https://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-v1.18.0.tar.gz --output crio-v1.18.0.tar.gz
- name: install crio runc, podman and skopeo
  become: true
  apt:
    pkg:
    - cri-o-runc
    - cri-tools
    - podman
    - podman-plugins
    - skopeo
    - catatonit
    - fuse-overlayfs
    - conmon
    - containers-common
    - containers-golang
    - containers-image
    - containernetworking-plugins
    - libslirp0
    - slirp4netns
    - uidmap
    - varlink

# Fix for a known issue, probably not needed in the future
# https://github.com/cri-o/cri-o/issues/3504
- name: replace line, Fix cri-o issue 3504
  become: true
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: 'apparmor_profile = "crio-default"'
    line: 'apparmor_profile = "crio-default-1.17.4"'
    backrefs: yes # w/o this, the operation isn't idempotent'

- name: Set crio's cgroup manager to systemd
  become: true
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: 'cgroup_manager = "cgroupfs"'
    line: 'cgroup_manager = "systemd"'
    backrefs: yes # w/o this, the operation isn't idempotent'

- name: Point crio.conf towards CNI plugins
  become: true
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: '"/opt/cni/bin/",'
    line: '"/opt/cni/bin/", "/usr/lib/cni/"'
    backrefs: yes # w/o this, the operation isn't idempotent'

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable crio
  become: true
  systemd:
    enabled: yes
    name: crio
    masked: no

- name: start crio
  become: true
  systemd:
    state: restarted
    name: crio

- name: crio smoke test
  become: true
  shell: 'crictl info'
