# Adding the crio repository and install
# Documentation at
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
# https://github.com/cri-o/cri-o
# https://medium.com/@raghwendrasingh1819/diy-kubernetes-cluster-with-cri-o-container-runtime-ubuntu-xenial-53e967c33dd9

# Currently the package_facts module is broken...
#- name: Gather installed packages
#  package_facts:
#    manager: auto
#  register: facts

# Workaround for broken package_facts module
- name: Check if crio {{ k8s_crio_version }} is installed
  shell: dpkg --list | grep cri-o-{{ k8s_crio_version }}
  register: crio_pkg
  ignore_errors: yes

- name: Add the overlay module
  become: true
  modprobe:
    name: overlay
    state: present
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'

- name: Add the br_netfilter module
  become: true
  modprobe:
    name: br_netfilter
    state: present
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'

- name: 99-kubernetes-cri.conf 1
  become: true
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'

- name: 99-kubernetes-cri.conf 2
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'

- name: 99-kubernetes-cri.conf 3
  become: true
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'

- name: add crio apt-key for {{ os_used }} {{ os_version }}
  become: true
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x{{ os_used }}_{{ os_version }}/Release.key"
    state: present
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'

- name: add crio apt repository {{ os_used }} {{ os_version }}
  become: true
  apt_repository:
    repo: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ os_used }}_{{ os_version }}/ /'
    state: present
    filename: devel:kubic:libcontainers:stable.list
    update_cache: yes
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'

- name: install crio {{ k8s_crio_version }}
  become: true
  apt:
    name: cri-o-{{ k8s_crio_version }}
    state: present
    update_cache: yes
  when: crio_pkg.rc != 0
  #when: '"cri-o-{{ k8s_crio_version }}" not in ansible_facts.packages'
  register: crio_installed

- name: fix/hold crio to version {{ k8s_crio_version }}
  become: true
  dpkg_selections:
    name: cri-o-{{ k8s_crio_version }}
    selection: hold
  when: crio_installed.changed == True

# Fix for a known issue, probably not needed in the future
# https://github.com/cri-o/cri-o/issues/3504
- name: replace line, Fix cri-o issue 3504
  become: true
  lineinfile: 
    path: /etc/crio/crio.conf
    regexp: 'apparmor_profile = "crio-default"' 
    line: 'apparmor_profile = "crio-default-{{ k8s_crio_version }}.2"'
    backrefs: yes # w/o this, the operation isn't idempotent'
  when: crio_installed.changed == True

- name: Copy crictl binary to /usr/local/bin
  become: true
  copy:
    src: packages/crictl
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes
  when: crio_installed.changed == True

- name: enable crio
  become: true
  systemd:
    enabled: yes
    name: crio
    masked: no
  when: crio_installed.changed == True

- name: start crio
  become: true
  systemd:
    state: started
    name: crio
  when: crio_installed.changed == True
