# Installing docker and containerd
# Documentation at
# https://linuxconfig.org/how-to-install-docker-on-ubuntu-20-04-lts-focal-fossa
# https://www.docker.com/blog/what-is-containerd-runtime/
# https://coreos.com/rkt/docs/latest/rkt-vs-other-projects.html

- name: install docker
  become: true
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Add the deployment user to the docker group
  become: true
  user:
    name: "{{ deploy_user }}"
    groups: docker
    append: yes

- name: Create directory for containerd configuration
  become: true
  file:
    path: /etc/containerd
    state: directory

- name: Create containerd configuration files
  become: true
  template:
    src: templates/docker-cni-containerd-config.toml.j2
    dest: /etc/containerd/config.toml

- name: Copy containerd.service configuration to the node
  become: true
  copy:
    src: templates/docker-cni-containerd_service.j2
    dest: /etc/systemd/system/containerd.service
    owner: root
    group: root

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable daemons
  become: true
  systemd:
    enabled: yes
    name: "{{ item }}"
    masked: no
  with_items:
    - docker
    - containerd

- name: start daemons
  become: true
  systemd:
    state: restarted
    name: "{{ item }}"
  with_items:
    - docker
    - containerd
