# Install K8s binaries
# Documentation at
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md
# https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md

- name: Copy kubectl binary to /usr/local/bin
  become: true
  copy:
    src: packages/k8s-{{ k8s_version }}-server/kubernetes/server/bin/kubectl
    dest: /usr/local/bin
    mode: '0755'
