# Making sure that the public key is available
- name: add authorized_key to non-root user
  authorized_key:
    user: pikube-deployer
    state: present
    key: "{{ lookup('file', '/home/pikube-deployer/.ssh/id_ed25519.pub') }}"
