# Install etcd
# Documentation at
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md
# https://github.com/mmumshad/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md
# https://github.com/etcd-io/etcd/releases

- name: Copy etcd binaries to /usr/local/bin
  become: true
  copy:
    src: "packages/etcd-{{ etcd_version }}-linux-arm64/{{ item }}"
    dest: /usr/local/bin
    mode: '0755'
  with_items:
    - etcd
    - etcdctl

- name: Create /etc/etcd/ directory
  become: true
  file:
    path: /etc/etcd/
    state: directory

- name: Create /var/lib/etcd directory
  become: true
  file:
    path: /var/lib/etcd
    state: directory

- name: Copy certificates to etcd configuration
  become: true
  copy:
    src: certificates/{{ item }}
    dest: /etc/etcd/{{ item }}
    mode: '0644'
  with_items:
    - "{{ cluster_name }}-ca.crt"
    - "{{ cluster_name }}-etcd.crt"

- name: Copy etcd key to etcd configuration
  become: true
  copy:
    src: certificates/{{ cluster_name }}-etcd.key
    dest: /etc/etcd/{{ cluster_name }}-etcd.key
    owner: root
    group: root
    mode: '0600'

- name: Assemble components for initial etcd cluster string
  set_fact:
    etcd_cluster_member: "{{ inventory_hostname }}=https://{{ ansible_host }}:2380"

- name: Assemble etcd initial cluster string
  set_fact:
    etcd_initial_cluster: "{{ groups['etcd_hosts'] | map('extract', hostvars, ['etcd_cluster_member']) | join(',') }}"

- name: Copy etcd configuration to the node
  become: true
  template:
    src: templates/etcd_service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes

- name: enable etcd
  become: true
  systemd:
    enabled: yes
    masked: no
    name: etcd

- name: start etcd
  become: true
  systemd:
    state: restarted
    name: etcd

# After etcd has restarted, the following command can be used to check:
# sudo ETCDCTL_API=3 etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/etcd/{{ cluster_name }}-ca.crt --cert=/etc/etcd/{{ cluster_name }}-etcd.crt --key=/etc/etcd/{{ cluster_name }}-etcd.key member list
