# Create certificate for the kube-controller-manager

- name: Generate an OpenSSL 2048 bit private RSA key for controller-manager
  openssl_privatekey:
    path: "certificates/{{ cluster_name }}-kube-controller-manager.key"
    size: 2048
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request for controller-manager
  openssl_csr:
    path: "certificates/{{ cluster_name }}-kube-controller-manager.csr"
    privatekey_path: "certificates/{{ cluster_name }}-kube-controller-manager.key"
    subject: "CN=system:kube-controller-manager"

- name: Sign the key with CA to obtain kube-controller-manager certificate
  openssl_certificate:
    path: "certificates/{{ cluster_name }}-kube-controller-manager.crt"
    csr_path: "certificates/{{ cluster_name }}-kube-controller-manager.csr"
    ownca_path: "certificates/{{ cluster_name }}-ca.crt"
    ownca_privatekey_path: "certificates/{{ cluster_name }}-ca.key"
    provider: ownca
