# Create certificate for the kube-scheduler

- name: Generate an OpenSSL 2048 bit private RSA key for the kube-scheduler
  openssl_privatekey:
    path: "certificates/{{ cluster_name }}-kube-scheduler.key"
    size: 2048
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request for the kube-scheduler
  openssl_csr:
    path: "certificates/{{ cluster_name }}-kube-scheduler.csr"
    privatekey_path: "certificates/{{ cluster_name }}-kube-scheduler.key"
    subject: "CN=system:kube-scheduler"

- name: Sign the kube-scheduler key with CA to obtain kube-scheduler cert
  openssl_certificate:
    path: "certificates/{{ cluster_name }}-kube-scheduler.crt"
    csr_path: "certificates/{{ cluster_name }}-kube-scheduler.csr"
    ownca_path: "certificates/{{ cluster_name }}-ca.crt"
    ownca_privatekey_path: "certificates/{{ cluster_name }}-ca.key"
    provider: ownca
