# Create certificate for the service account

- name: Generate an OpenSSL 2048 bit private RSA key for service account
  openssl_privatekey:
    path: "certificates/{{ cluster_name }}-service-account.key"
    size: 2048
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request for service account
  openssl_csr:
    path: "certificates/{{ cluster_name }}-service-account.csr"
    privatekey_path: "certificates/{{ cluster_name }}-service-account.key"
    subject: "CN=system:service-accounts"

- name: Sign the key with CA to obtain service-account certificate
  openssl_certificate:
    path: "certificates/{{ cluster_name }}-service-account.crt"
    csr_path: "certificates/{{ cluster_name }}-service-account.csr"
    ownca_path: "certificates/{{ cluster_name }}-ca.crt"
    ownca_privatekey_path: "certificates/{{ cluster_name }}-ca.key"
    provider: ownca
