# Generate the kubelet configurations

- name: Create kubelet configuration files
  shell: "kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority=certificates/{{ cluster_name }}-ca.crt \
    --embed-certs=true \
    --server=https://{{ groups['proxies'][0] }}:6443 \
    --kubeconfig=configuration/{{ item }}.kubeconfig &&
    kubectl config set-credentials system:node:{{ item }} \
    --client-certificate=certificates/{{ cluster_name }}-worker-{{ item }}.crt
    --client-key=certificates/{{ cluster_name }}-worker-{{ item }}.key
    --embed-certs=true \
    --kubeconfig=configuration/{{ item }}.kubeconfig &&
    kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user=system:node:{{ item }} \
    --kubeconfig=configuration/{{ item }}.kubeconfig &&
    kubectl config use-context default --kubeconfig=configuration/{{ item }}.kubeconfig"
  with_items: "{{ groups['workers'] }}"
